/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace processo
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Resultado : TBase
  {
    private bool _sinal;
    private string _mensagem;

    public bool Sinal
    {
      get
      {
        return _sinal;
      }
      set
      {
        __isset.sinal = true;
        this._sinal = value;
      }
    }

    public string Mensagem
    {
      get
      {
        return _mensagem;
      }
      set
      {
        __isset.mensagem = true;
        this._mensagem = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool sinal;
      public bool mensagem;
    }

    public Resultado() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Bool) {
              Sinal = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Mensagem = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Resultado");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.sinal) {
        field.Name = "sinal";
        field.Type = TType.Bool;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Sinal);
        oprot.WriteFieldEnd();
      }
      if (Mensagem != null && __isset.mensagem) {
        field.Name = "mensagem";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Mensagem);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Resultado(");
      sb.Append("Sinal: ");
      sb.Append(Sinal);
      sb.Append(",Mensagem: ");
      sb.Append(Mensagem);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
