/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package processo;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Resultado implements org.apache.thrift.TBase<Resultado, Resultado._Fields>, java.io.Serializable, Cloneable, Comparable<Resultado> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Resultado");

  private static final org.apache.thrift.protocol.TField SINAL_FIELD_DESC = new org.apache.thrift.protocol.TField("sinal", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField MENSAGEM_FIELD_DESC = new org.apache.thrift.protocol.TField("mensagem", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ResultadoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ResultadoTupleSchemeFactory());
  }

  public boolean sinal; // required
  public String mensagem; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SINAL((short)1, "sinal"),
    MENSAGEM((short)2, "mensagem");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SINAL
          return SINAL;
        case 2: // MENSAGEM
          return MENSAGEM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SINAL_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SINAL, new org.apache.thrift.meta_data.FieldMetaData("sinal", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.MENSAGEM, new org.apache.thrift.meta_data.FieldMetaData("mensagem", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Resultado.class, metaDataMap);
  }

  public Resultado() {
  }

  public Resultado(
    boolean sinal,
    String mensagem)
  {
    this();
    this.sinal = sinal;
    setSinalIsSet(true);
    this.mensagem = mensagem;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Resultado(Resultado other) {
    __isset_bitfield = other.__isset_bitfield;
    this.sinal = other.sinal;
    if (other.isSetMensagem()) {
      this.mensagem = other.mensagem;
    }
  }

  public Resultado deepCopy() {
    return new Resultado(this);
  }

  @Override
  public void clear() {
    setSinalIsSet(false);
    this.sinal = false;
    this.mensagem = null;
  }

  public boolean isSinal() {
    return this.sinal;
  }

  public Resultado setSinal(boolean sinal) {
    this.sinal = sinal;
    setSinalIsSet(true);
    return this;
  }

  public void unsetSinal() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SINAL_ISSET_ID);
  }

  /** Returns true if field sinal is set (has been assigned a value) and false otherwise */
  public boolean isSetSinal() {
    return EncodingUtils.testBit(__isset_bitfield, __SINAL_ISSET_ID);
  }

  public void setSinalIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SINAL_ISSET_ID, value);
  }

  public String getMensagem() {
    return this.mensagem;
  }

  public Resultado setMensagem(String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

  public void unsetMensagem() {
    this.mensagem = null;
  }

  /** Returns true if field mensagem is set (has been assigned a value) and false otherwise */
  public boolean isSetMensagem() {
    return this.mensagem != null;
  }

  public void setMensagemIsSet(boolean value) {
    if (!value) {
      this.mensagem = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SINAL:
      if (value == null) {
        unsetSinal();
      } else {
        setSinal((Boolean)value);
      }
      break;

    case MENSAGEM:
      if (value == null) {
        unsetMensagem();
      } else {
        setMensagem((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SINAL:
      return Boolean.valueOf(isSinal());

    case MENSAGEM:
      return getMensagem();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SINAL:
      return isSetSinal();
    case MENSAGEM:
      return isSetMensagem();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Resultado)
      return this.equals((Resultado)that);
    return false;
  }

  public boolean equals(Resultado that) {
    if (that == null)
      return false;

    boolean this_present_sinal = true;
    boolean that_present_sinal = true;
    if (this_present_sinal || that_present_sinal) {
      if (!(this_present_sinal && that_present_sinal))
        return false;
      if (this.sinal != that.sinal)
        return false;
    }

    boolean this_present_mensagem = true && this.isSetMensagem();
    boolean that_present_mensagem = true && that.isSetMensagem();
    if (this_present_mensagem || that_present_mensagem) {
      if (!(this_present_mensagem && that_present_mensagem))
        return false;
      if (!this.mensagem.equals(that.mensagem))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Resultado other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSinal()).compareTo(other.isSetSinal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSinal()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sinal, other.sinal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMensagem()).compareTo(other.isSetMensagem());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMensagem()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mensagem, other.mensagem);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Resultado(");
    boolean first = true;

    sb.append("sinal:");
    sb.append(this.sinal);
    first = false;
    if (!first) sb.append(", ");
    sb.append("mensagem:");
    if (this.mensagem == null) {
      sb.append("null");
    } else {
      sb.append(this.mensagem);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ResultadoStandardSchemeFactory implements SchemeFactory {
    public ResultadoStandardScheme getScheme() {
      return new ResultadoStandardScheme();
    }
  }

  private static class ResultadoStandardScheme extends StandardScheme<Resultado> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Resultado struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SINAL
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.sinal = iprot.readBool();
              struct.setSinalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MENSAGEM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mensagem = iprot.readString();
              struct.setMensagemIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Resultado struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SINAL_FIELD_DESC);
      oprot.writeBool(struct.sinal);
      oprot.writeFieldEnd();
      if (struct.mensagem != null) {
        oprot.writeFieldBegin(MENSAGEM_FIELD_DESC);
        oprot.writeString(struct.mensagem);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ResultadoTupleSchemeFactory implements SchemeFactory {
    public ResultadoTupleScheme getScheme() {
      return new ResultadoTupleScheme();
    }
  }

  private static class ResultadoTupleScheme extends TupleScheme<Resultado> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Resultado struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSinal()) {
        optionals.set(0);
      }
      if (struct.isSetMensagem()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSinal()) {
        oprot.writeBool(struct.sinal);
      }
      if (struct.isSetMensagem()) {
        oprot.writeString(struct.mensagem);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Resultado struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.sinal = iprot.readBool();
        struct.setSinalIsSet(true);
      }
      if (incoming.get(1)) {
        struct.mensagem = iprot.readString();
        struct.setMensagemIsSet(true);
      }
    }
  }

}

